package ping.mc.game.item.ability;

public enum AbilityType {
    PASSIVE,
    SHIFT,
    RIGHT_CLICK,
    LEFT_CLICK,
    SHIFT_RIGHT_CLICK,
    SHIFT_LEFT_CLICK,
    BLOCK_RIGHT_CLICK,
    BLOCK_LEFT_CLICK,
    SHIFT_BLOCK_RIGHT_CLICK,
    SHIFT_BLOCK_LEFT_CLICK,
    ENTITY_RIGHT_CLICK,
    ENTITY_LEFT_CLICK,
    SHIFT_ENTITY_RIGHT_CLICK,
    SHIFT_ENTITY_LEFT_CLICK,
}
