name: APInguin
version: v0.0.1-alpha.1
main: ping.apinguin.APInguin
description: Allows you to easily create items with your java plugin!
api-version: 1.13
load: STARTUP
authors:
  - "ItsPinguin"

depend:
  - NBTAPI

commands:
  apinguin:
    description: APInguin's command